package org.telegram.tasks.localization

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.BufferedWriter
import java.io.File
import java.nio.charset.StandardCharsets
import kotlin.text.iterator

/**
 * Generates [org.telegram.localization.NamespaceLocalizationUtils.java]
 * containing one lookup method per extra string namespace, e.g.
 * [getLocalizationAssetNeko], plus a generic
 * [getLocalizationAsset(java.util.Locale, String)] accessor used by
 * [org.telegram.messenger.LocaleController] at runtime.
 *
 * The original [GenerateLocalizationUtilsJavaTask] and its
 * [org.telegram.localization.LocalizationUtils.getLocalizationAsset] method
 * are left untouched.
 */
@CacheableTask
abstract class GenerateNamespaceLocalizationUtilsJavaTask : DefaultTask() {

    // values/strings_*.xml, decides which namespaces exist in the default (en) pack.
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val defaultLocalizationFiles: ConfigurableFileCollection

    // values-*/strings_*.xml.
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val localizationFiles: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val javaOutputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        // namespace -> language tags which exist for that namespace.
        val tagsByNamespace = sortedMapOf<String, MutableSet<String>>()

        for (file in defaultLocalizationFiles.files) {
            tagsByNamespace
                .getOrPut(getNamespace(file)) { sortedSetOf() }
                .add("en")
        }

        for (file in localizationFiles.files) {
            tagsByNamespace
                .getOrPut(getNamespace(file)) { sortedSetOf() }
                .add(getLanguageTag(file))
        }

        generateJava(
            javaDir = javaOutputDir.get().asFile,
            tagsByNamespace = tagsByNamespace
        )
    }

    private fun generateJava(
        javaDir: File,
        tagsByNamespace: Map<String, Set<String>>
    ) {
        if (tagsByNamespace.isEmpty()) {
            return
        }

        val packageName = "org.telegram.localization"
        val packageDir = javaDir.resolve(packageName.replace('.', '/'))

        packageDir.mkdirs()

        packageDir.resolve("NamespaceLocalizationUtils.java")
            .bufferedWriter(StandardCharsets.UTF_8)
            .use { java ->
                java.appendLine("package $packageName;")
                java.appendLine()
                java.appendLine("import java.util.Locale;")
                java.appendLine()
                java.appendLine("/** Generated by GenerateNamespaceLocalizationUtilsJavaTask. Do not edit. */")
                java.appendLine("public final class NamespaceLocalizationUtils {")
                java.appendLine()
                java.appendLine("    private NamespaceLocalizationUtils() {")
                java.appendLine("    }")
                java.appendLine()
                java.appendLine("    public static String[] getNamespaces() {")
                java.appendLine("        return new String[] {")

                for (namespace in tagsByNamespace.keys) {
                    java.append("            \"")
                    java.append(escapeJavaString(namespace))
                    java.appendLine("\",")
                }

                java.appendLine("        };")
                java.appendLine("    }")
                java.appendLine()
                java.appendLine("    public static String getLocalizationAsset(Locale locale, String namespace) {")
                java.appendLine("        if (namespace == null) {")
                java.appendLine("            return null;")
                java.appendLine("        }")
                java.appendLine()
                java.appendLine("        switch (namespace) {")

                for (namespace in tagsByNamespace.keys) {
                    java.append("            case \"")
                    java.append(escapeJavaString(namespace))
                    java.append("\": return getLocalizationAsset")
                    java.append(namespace.replaceFirstChar { it.uppercaseChar() })
                    java.appendLine("(locale);")
                }

                java.appendLine("            default: return null;")
                java.appendLine("        }")
                java.appendLine("    }")
                java.appendLine()

                for ((namespace, tags) in tagsByNamespace) {
                    appendLookupMethod(
                        java = java,
                        namespace = namespace,
                        tags = tags
                    )
                }

                java.appendLine("}")
            }
    }

    // getLocalizationAssetNeko(Locale), getLocalizationAssetNekox(Locale), ...
    private fun appendLookupMethod(
        java: BufferedWriter,
        namespace: String,
        tags: Set<String>
    ) {
        val methodName = "getLocalizationAsset" +
                namespace.replaceFirstChar { it.uppercaseChar() }

        val defaultAsset = if (tags.contains("en")) {
            getLocalizationAssetName("en", namespace)
        } else {
            null
        }

        java.appendLine("    public static String $methodName(Locale locale) {")
        java.appendLine("        if (locale == null) {")
        java.appendLine("            return null;")
        java.appendLine("        }")
        java.appendLine()
        java.appendLine("        final String tag = locale.toLanguageTag();")
        java.appendLine()
        java.appendLine("        switch (tag) {")

        for (tag in tags) {
            java.append("            case \"")
            java.append(escapeJavaString(tag))
            java.append("\": return \"")
            java.append(getLocalizationAssetName(tag, namespace))
            java.appendLine("\";")
        }

        java.appendLine("        }")
        java.appendLine()
        java.appendLine("        final String language = locale.getLanguage();")
        java.appendLine()
        java.appendLine("        switch (language) {")

        // language -> best-matching tag. Prefer an exact language tag over
        // region variants; otherwise take the first (sorted) variant.
        val tagsByLanguage = sortedMapOf<String, String>()

        for (tag in tags) {
            val language = tag.substringBefore('-')

            if (!tagsByLanguage.containsKey(language) || tag == language) {
                tagsByLanguage[language] = tag
            }
        }

        for ((language, tag) in tagsByLanguage) {
            java.append("            case \"")
            java.append(escapeJavaString(language))
            java.append("\": return \"")
            java.append(getLocalizationAssetName(tag, namespace))
            java.appendLine("\";")
        }

        if (defaultAsset != null) {
            java.append("            default: return \"")
            java.append(defaultAsset)
            java.appendLine("\";")
        } else {
            java.appendLine("            default: return null;")
        }

        java.appendLine("        }")
        java.appendLine("    }")
        java.appendLine()
    }

    private fun getLocalizationAssetName(
        languageTag: String,
        namespace: String
    ): String {
        val normalized = buildString(languageTag.length) {
            for (char in languageTag) {
                when {
                    char in 'A'..'Z' -> append(char.lowercaseChar())
                    char in 'a'..'z' ||
                            char in '0'..'9' ||
                            char == '_' -> append(char)

                    else -> append('_')
                }
            }
        }

        return "localization_${normalized}_$namespace.bin"
    }

    // strings_neko.xml -> "neko".
    private fun getNamespace(
        file: File
    ): String {
        val name = file.name

        if (!name.startsWith("strings_") || !name.endsWith(".xml")) {
            error("Invalid namespaced strings file: ${file.absolutePath}")
        }

        val namespace = name
            .removePrefix("strings_")
            .removeSuffix(".xml")

        if (namespace.isEmpty() || !namespace.matches(Regex("[a-z0-9_]+"))) {
            error(
                "Invalid strings namespace \"$namespace\" in ${file.absolutePath}: " +
                        "expected lowercase letters, digits or underscores"
            )
        }

        return namespace
    }

    private fun getLanguageTag(
        file: File
    ): String {
        val directoryName = file.parentFile.name

        if (!directoryName.startsWith("values-")) {
            error("Invalid localization directory: ${file.absolutePath}")
        }

        val qualifier = directoryName.substring("values-".length)

        if (qualifier.isEmpty()) {
            error("Unable to determine language code: ${file.absolutePath}")
        }

        if (qualifier.startsWith("b+")) {
            return qualifier.substring(2).replace('+', '-')
        }

        val regionIndex = qualifier.indexOf("-r")

        if (regionIndex != -1) {
            val language = qualifier.substring(0, regionIndex)
            val region = qualifier.substring(regionIndex + 2)

            return "$language-$region"
        }

        return qualifier
    }

    private fun escapeJavaString(
        value: String
    ): String {
        return value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
    }
}